### ISSUE TITLE
Document nRF8001 setup data format

### ISSUE THREAD

**Issue by sandeepmistry** [lizardo/nrf8001#1]
Just wanted to thank you for your work on the repo. I was able to use it as a starting point to create an Arduino lib that doesn't use nRFgo studio, and creates setup messages dynamically at runtime.

https://github.com/sandeepmistry/arduino-BLEPeripheral

If you're interested, I could share/document the additional fields/structures.

**Comment by lizardo** [comment]
Sorry for the very late response. It's been a long time since I last played with nRF8001 and for some reason your message did not trigger any mail notifications at the time.

Glad to hear my experiments were useful :) I would welcome any documentation you have for the format. In a quick search I found these:
- https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/nRF8001.cpp (the source file for your project)
- https://github.com/NordicSemiconductor/ble-sdk-arduino/tree/master/documentation/libraries/BLE/examples/ble_modify_setup_data (slightly updated version for the .docx shared by Nordic on their forum)

**Comment by sandeepmistry** [comment]
@lizardo no worries on the late response.

We can extract documentation from: https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/nRF8001.cpp

Is this still something you'd be interested in, given you that you are not actively using the nRF8001?

**Comment by lizardo** [comment]
Sure! I believe it will also benefit other people who want to automate customization of nRF8001 services.

My suggestion is to use github's wiki for this documentation, so it is easier to update. Do you mind starting a initial version on your project's wiki page?

In next weeks, I will have little time to contribute, but I'll help to fill any missing information based on my future experiments.

(I'll keep this issue open until the setup format is fully understood.)

**Comment by sandeepmistry** [comment]
@lizardo I'm pretty tight on time at the moment, so this task is on my back burner for now.

**Comment by sandeepmistry** [comment]
@lizardo Nordic has updated their document see: https://github.com/NordicSemiconductor/ble-sdk-arduino/tree/master/documentation/libraries/BLE/examples/ble_modify_setup_data

As per this post: https://devzone.nordicsemi.com/question/3949/spec-for-nrf8001-setup-format/?answer=38535#post-id-38535

**Comment by lizardo** [comment]
@sandeepmistry yes, this document has been around for some time. I haven't checked how complete it is though.

At the moment I'm using nRF51822 for BLE stuff, which does not use setup data. Not sure yet when I will have the time to go back to nRF8001...

**Comment by sandeepmistry** [comment]
@lizardo yep, but it looks like this commit documents all of the structures of the setup message structure: https://github.com/NordicSemiconductor/ble-sdk-arduino/commit/0fe2b6e8a57d6b1131bdcec5839180c532896abb#diff-f527a3ff776d442c7d0529624939f36b

Maybe we should close this issue for now then?

**Comment by lizardo** [comment]
@sandeepmistry Sure, the version I looked at long time ago was incomplete, but they seem to have completed it on this latest version.

Thanks for bringing it up!
